// Code generated by github.com/utrack/pontoon/docgen. DO NOT EDIT.

package test

const DocYAML = `checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
services:
  Handler:
    id: github.com/utrack/pontoon/test.Handler
    type: service
    pkg_path: github.com/utrack/pontoon/test
    type_name: Handler
    file: /home/u/github/utrack/pontoon/test/h1.go
    line: 12
    comment: |
      Handler struct comment
    methods:
      OpenAPI:
        file: /home/u/github/utrack/pontoon/test/handler.pontoon.go
        line: 6
        output_type: string
      RegisterHTTP:
        file: /home/u/github/utrack/pontoon/test/reg.go
        line: 9
      ServiceOptions:
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 115
        output_type: '[]github.com/utrack/pontoon/sdesc.ServiceOption'
      ifaceReturn:
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 82
        input_type: github.com/utrack/pontoon/test.iterateRequest
        output_type: interface{}
        formed_error: true
      ifaceReturnAny:
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 86
        input_type: github.com/utrack/pontoon/test.iterateRequest
        output_type: any
        formed_error: true
      iterateProducts:
        comment: |
          IterateProducts comment
          Includes imported package
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 74
        input_type: github.com/utrack/pontoon/test.iterateRequest
        output_type: github.com/utrack/pontoon/test2.IterateResponse
        formed_error: true
      jsonWithDirs:
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 111
        input_type: github.com/utrack/pontoon/test.jsonWithDirectives
        formed_error: true
      mapReturn:
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 107
        input_type: github.com/utrack/pontoon/test.iterateRequest
        output_type: map[string]github.com/utrack/pontoon/test2.IterateResponse
        formed_error: true
      nonAnnotIn:
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 78
        input_type: github.com/utrack/pontoon/test.nonAnnotJSON
        output_type: interface{}
        formed_error: true
      rawHandler:
        comment: |
          This is a "raw" handler that cannot be annotated.
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 95
      sliceInObjReturn:
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 103
        output_type: github.com/utrack/pontoon/test.jsonWithArrayOfStructs
        formed_error: true
      sliceReturn:
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 99
        input_type: github.com/utrack/pontoon/test.iterateRequest
        output_type: '[]github.com/utrack/pontoon/test2.IterateResponse'
        formed_error: true
      zeroReturn:
        file: /home/u/github/utrack/pontoon/test/h1.go
        line: 90
        input_type: github.com/utrack/pontoon/test.iterateRequest
        formed_error: true
types:
  github.com/utrack/pontoon/sdesc.ServiceOption:
    package: github.com/utrack/pontoon/sdesc
    name: ServiceOption
    file: /home/u/github/utrack/pontoon/sdesc/options.go
    line: 25
    is_struct: false
  github.com/utrack/pontoon/test.dummyStruct:
    package: github.com/utrack/pontoon/test
    name: dummyStruct
    file: /home/u/github/utrack/pontoon/test/h1.go
    line: 66
    fields:
      - name: DummyField
        type: string
    is_struct: true
  github.com/utrack/pontoon/test.iterateEmbedded:
    package: github.com/utrack/pontoon/test
    name: iterateEmbedded
    file: /home/u/github/utrack/pontoon/test/h1.go
    line: 37
    comment: |
      iterateEmbedded has an Embed comment
    fields:
      - name: PageToken
        type: string
        comment: |
          PageToken is a token for the next page.
          Pass an empty PageToken if you want to request the first page,
          and use a token from the response as PageToken to get the next page.
        tags: in:"query=page_token"
    is_struct: true
  github.com/utrack/pontoon/test.iterateRequest:
    package: github.com/utrack/pontoon/test
    name: iterateRequest
    file: /home/u/github/utrack/pontoon/test/h1.go
    line: 17
    comment: |
      Request comment
      Request line 2
    fields:
      - name: iterateEmbedded
        type: github.com/utrack/pontoon/test.iterateEmbedded
        is_embedded: true
      - name: Foo
        type: int64
        tags: in:"query=foo"
      - name: Local
        type: string
        comment: |
          Local describes Some Stuff(tm). Required field.
        tags: in:"query=local;required"
      - name: LocalWithDefault
        type: string
        tags: in:"query=local_default;required;default=foobarbaz"
      - name: SliceStrings
        type: '[]string'
        tags: foo:"bar"
        is_array:
          type: string
      - name: Maps
        type: map[string]github.com/utrack/pontoon/test.mapped
        tags: faa:"faw"
        is_map:
          key: string
          value: github.com/utrack/pontoon/test.mapped
      - name: Recursive
        type: github.com/utrack/pontoon/test.iterateRequest
        tags: in:"body=json"
        nullable: true
    is_struct: true
  github.com/utrack/pontoon/test.jsonWithArrayOfStructs:
    package: github.com/utrack/pontoon/test
    name: jsonWithArrayOfStructs
    file: /home/u/github/utrack/pontoon/test/h1.go
    line: 62
    fields:
      - name: Ret
        type: '[]github.com/utrack/pontoon/test.dummyStruct'
        is_array:
          type: github.com/utrack/pontoon/test.dummyStruct
    is_struct: true
  github.com/utrack/pontoon/test.jsonWithDirectives:
    package: github.com/utrack/pontoon/test
    name: jsonWithDirectives
    file: /home/u/github/utrack/pontoon/test/h1.go
    line: 56
    comment: |
      jsonWithDirectives describes a JSON-marshaled request with additional 'in' directives.
    fields:
      - name: RequiredWithDefault
        type: string
        tags: json:"with_default,omitempty" in:"required;default=1234"
      - name: RequiredOnly
        type: string
        tags: in:"required"
    is_struct: true
  github.com/utrack/pontoon/test.mapped:
    package: github.com/utrack/pontoon/test
    name: mapped
    file: /home/u/github/utrack/pontoon/test/h1.go
    line: 34
    is_struct: true
  github.com/utrack/pontoon/test.nonAnnotJSON:
    package: github.com/utrack/pontoon/test
    name: nonAnnotJSON
    file: /home/u/github/utrack/pontoon/test/h1.go
    line: 45
    comment: |
      nonAnnotJSON represents a 'raw' JSON struct without annotations with an embed no-annotated one
    fields:
      - name: nonAnnotJSON2
        type: github.com/utrack/pontoon/test.nonAnnotJSON2
        comment: |
          TODO *nonAnnotJSON blows up the stack
        is_embedded: true
      - name: Foo
        type: string
        tags: json:"foo"
    is_struct: true
  github.com/utrack/pontoon/test.nonAnnotJSON2:
    package: github.com/utrack/pontoon/test
    name: nonAnnotJSON2
    file: /home/u/github/utrack/pontoon/test/h1.go
    line: 51
    fields:
      - name: Bar
        type: string
        tags: json:"bar"
    is_struct: true
  github.com/utrack/pontoon/test2.IterateResponse:
    package: github.com/utrack/pontoon/test2
    name: IterateResponse
    file: /home/u/github/utrack/pontoon/test2/test2.go
    line: 3
    fields:
      - name: Resp
        type: string
        tags: json:"resp"
    is_struct: true
`
