// Code generated by utrack/pontoon. DO NOT EDIT.
// Source: github.com/utrack/pontoon/test

package test

func (s Handler) OpenAPI() string {
	return `{
    "components": {
      "schemas": {
        "test.iterateEmbedded": {
          "description": "Has an Embed comment",
          "properties": {
            "PageToken": {
              "description": "A token for the next page.\nPass an empty PageToken if you want to request the first page,\nand use a token from the response as PageToken to get the next page.",
              "type": "string"
            }
          },
          "type": "object"
        },
        "test.iterateRequest": {
          "allOf": [
            {
              "$ref": "#/components/schemas/test.iterateEmbedded"
            }
          ],
          "description": "Request comment\nRequest line 2",
          "properties": {
            "Local": {
              "description": "Describes Some Stuff(tm)",
              "type": "string"
            },
            "Maps": {
              "additionalProperties": {
                "$ref": "#/components/schemas/test.mapped"
              },
              "type": "object"
            },
            "Recursive": {
              "anyOf": [
                {
                  "type": "null"
                },
                {
                  "$ref": "#/components/schemas/test.iterateRequest"
                }
              ]
            },
            "SliceStrings": {
              "items": {
                "type": "string"
              },
              "nullable": true,
              "type": "array"
            }
          },
          "type": "object"
        },
        "test.mapped": {
          "type": "object"
        },
        "test2.IterateResponse": {
          "properties": {
            "resp": {
              "type": "string"
            }
          },
          "type": "object"
        }
      }
    },
    "info": {
      "title": "github.com/utrack/pontoon/test",
      "version": "1-autogen"
    },
    "openapi": "3.1.0",
    "paths": {
      "/v1/products/iterate": {
        "get": {
          "description": "IterateProducts comment\nIncludes imported package\n",
          "parameters": [
            {
              "description": "A token for the next page.\nPass an empty page_token if you want to request the first page,\nand use a token from the response as page_token to get the next page.",
              "in": "query",
              "name": "page_token",
              "schema": {
                "description": "A token for the next page.\nPass an empty PageToken if you want to request the first page,\nand use a token from the response as PageToken to get the next page.",
                "type": "string"
              }
            },
            {
              "description": "Describes Some Stuff(tm)",
              "in": "query",
              "name": "local",
              "schema": {
                "description": "Describes Some Stuff(tm)",
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "$ref": "#/components/schemas/test.iterateRequest"
                    }
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/test2.IterateResponse"
                  }
                }
              },
              "description": "success"
            },
            "default": {
              "description": ""
            }
          },
          "tags": [
            "test.Handler"
          ]
        },
        "post": {
          "description": "IterateProducts comment\nIncludes imported package\n",
          "parameters": [
            {
              "description": "A token for the next page.\nPass an empty page_token if you want to request the first page,\nand use a token from the response as page_token to get the next page.",
              "in": "query",
              "name": "page_token",
              "schema": {
                "description": "A token for the next page.\nPass an empty PageToken if you want to request the first page,\nand use a token from the response as PageToken to get the next page.",
                "type": "string"
              }
            },
            {
              "description": "Describes Some Stuff(tm)",
              "in": "query",
              "name": "local",
              "schema": {
                "description": "Describes Some Stuff(tm)",
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "$ref": "#/components/schemas/test.iterateRequest"
                    }
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/test2.IterateResponse"
                  }
                }
              },
              "description": "success"
            },
            "default": {
              "description": ""
            }
          },
          "tags": [
            "test.Handler"
          ]
        }
      },
      "/v1/products/iterate/create": {
        "post": {
          "description": "IterateProducts comment\nIncludes imported package\n",
          "parameters": [
            {
              "description": "A token for the next page.\nPass an empty page_token if you want to request the first page,\nand use a token from the response as page_token to get the next page.",
              "in": "query",
              "name": "page_token",
              "schema": {
                "description": "A token for the next page.\nPass an empty PageToken if you want to request the first page,\nand use a token from the response as PageToken to get the next page.",
                "type": "string"
              }
            },
            {
              "description": "Describes Some Stuff(tm)",
              "in": "query",
              "name": "local",
              "schema": {
                "description": "Describes Some Stuff(tm)",
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "$ref": "#/components/schemas/test.iterateRequest"
                    }
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/test2.IterateResponse"
                  }
                }
              },
              "description": "success"
            },
            "default": {
              "description": ""
            }
          },
          "tags": [
            "test.Handler"
          ]
        }
      },
      "/v1/test/return/interface": {
        "get": {
          "parameters": [
            {
              "description": "A token for the next page.\nPass an empty page_token if you want to request the first page,\nand use a token from the response as page_token to get the next page.",
              "in": "query",
              "name": "page_token",
              "schema": {
                "description": "A token for the next page.\nPass an empty PageToken if you want to request the first page,\nand use a token from the response as PageToken to get the next page.",
                "type": "string"
              }
            },
            {
              "description": "Describes Some Stuff(tm)",
              "in": "query",
              "name": "local",
              "schema": {
                "description": "Describes Some Stuff(tm)",
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "$ref": "#/components/schemas/test.iterateRequest"
                    }
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "content": {
                "application/json": {
                  "schema": {}
                }
              },
              "description": "success"
            },
            "default": {
              "description": ""
            }
          },
          "tags": [
            "test.Handler"
          ]
        }
      },
      "/v1/test/return/interface-any": {
        "get": {
          "parameters": [
            {
              "description": "A token for the next page.\nPass an empty page_token if you want to request the first page,\nand use a token from the response as page_token to get the next page.",
              "in": "query",
              "name": "page_token",
              "schema": {
                "description": "A token for the next page.\nPass an empty PageToken if you want to request the first page,\nand use a token from the response as PageToken to get the next page.",
                "type": "string"
              }
            },
            {
              "description": "Describes Some Stuff(tm)",
              "in": "query",
              "name": "local",
              "schema": {
                "description": "Describes Some Stuff(tm)",
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "$ref": "#/components/schemas/test.iterateRequest"
                    }
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "content": {
                "application/json": {
                  "schema": {}
                }
              },
              "description": "success"
            },
            "default": {
              "description": ""
            }
          },
          "tags": [
            "test.Handler"
          ]
        }
      },
      "/v1/test/return/map": {
        "get": {
          "parameters": [
            {
              "description": "A token for the next page.\nPass an empty page_token if you want to request the first page,\nand use a token from the response as page_token to get the next page.",
              "in": "query",
              "name": "page_token",
              "schema": {
                "description": "A token for the next page.\nPass an empty PageToken if you want to request the first page,\nand use a token from the response as PageToken to get the next page.",
                "type": "string"
              }
            },
            {
              "description": "Describes Some Stuff(tm)",
              "in": "query",
              "name": "local",
              "schema": {
                "description": "Describes Some Stuff(tm)",
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "$ref": "#/components/schemas/test.iterateRequest"
                    }
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "content": {
                "application/json": {
                  "schema": {
                    "additionalProperties": {
                      "$ref": "#/components/schemas/test2.IterateResponse"
                    },
                    "type": "object"
                  }
                }
              },
              "description": "success"
            },
            "default": {
              "description": ""
            }
          },
          "tags": [
            "test.Handler"
          ]
        }
      },
      "/v1/test/return/return-nothing": {
        "get": {
          "parameters": [
            {
              "description": "A token for the next page.\nPass an empty page_token if you want to request the first page,\nand use a token from the response as page_token to get the next page.",
              "in": "query",
              "name": "page_token",
              "schema": {
                "description": "A token for the next page.\nPass an empty PageToken if you want to request the first page,\nand use a token from the response as PageToken to get the next page.",
                "type": "string"
              }
            },
            {
              "description": "Describes Some Stuff(tm)",
              "in": "query",
              "name": "local",
              "schema": {
                "description": "Describes Some Stuff(tm)",
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "$ref": "#/components/schemas/test.iterateRequest"
                    }
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "content": {
                "application/json": {}
              },
              "description": "success"
            },
            "default": {
              "description": ""
            }
          },
          "tags": [
            "test.Handler"
          ]
        }
      },
      "/v1/test/return/slice": {
        "get": {
          "parameters": [
            {
              "description": "A token for the next page.\nPass an empty page_token if you want to request the first page,\nand use a token from the response as page_token to get the next page.",
              "in": "query",
              "name": "page_token",
              "schema": {
                "description": "A token for the next page.\nPass an empty PageToken if you want to request the first page,\nand use a token from the response as PageToken to get the next page.",
                "type": "string"
              }
            },
            {
              "description": "Describes Some Stuff(tm)",
              "in": "query",
              "name": "local",
              "schema": {
                "description": "Describes Some Stuff(tm)",
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "$ref": "#/components/schemas/test.iterateRequest"
                    }
                  ]
                }
              }
            }
          },
          "responses": {
            "200": {
              "content": {
                "application/json": {
                  "schema": {
                    "items": {
                      "$ref": "#/components/schemas/test2.IterateResponse"
                    },
                    "nullable": true,
                    "type": "array"
                  }
                }
              },
              "description": "success"
            },
            "default": {
              "description": ""
            }
          },
          "tags": [
            "test.Handler"
          ]
        }
      }
    }
  }`
}
