/*
Package docregistry provides a registry for documentation entities extracted from the comments.
Every docfile generated by the docgen tool is registered here.
*/
package docregistry

import (
	"reflect"
	"runtime"
	"strings"

	"github.com/utrack/pontoon/v2/docgen"
	"gopkg.in/yaml.v3"

	"github.com/pkg/errors"
)

type registry struct {
	finalDoc *docgen.YAMLDoc
}

func newRegistry() *registry {
	return &registry{finalDoc: &docgen.YAMLDoc{
		Checksum:  "no-global-checksum",
		Types:     make(map[string]docgen.YAMLType),
		Functions: make(map[string]docgen.YAMLMethod),
	}}
}

var global = newRegistry()

// MustRegister registers the generated docfile in the global registry.
// It panics if the registration fails. The panic will contain the error description,
// source file name and line number.
func MustRegister(yaml string) {
	err := global.registerYaml(yaml)
	if err != nil {
		panic(errors.Wrap(err, "when registering generated docfile"))
	}
}

func (r *registry) registerYaml(yaml string) error {
	doc, err := parseYaml([]byte(yaml))
	if err != nil {
		return errors.Wrap(err, "when parsing YAML to YAMLDoc")
	}

	for k, v := range doc.Types {
		if _, ok := r.finalDoc.Types[k]; ok {
			// TODO deep compare and error when not equal
			return errors.Errorf("type '%v' already registered", k)
		}
		r.finalDoc.Types[k] = v
	}

	for k, v := range doc.Functions {
		if _, ok := r.finalDoc.Functions[k]; ok {
			// TODO deep compare and error when not equal
			return errors.Errorf("function '%v' already registered", k)
		}
		r.finalDoc.Functions[k] = v
	}

	return nil
}

func parseYaml(in []byte) (*docgen.YAMLDoc, error) {
	var ret docgen.YAMLDoc

	err := yaml.Unmarshal([]byte(in), &ret)
	return &ret, err
}

func For(in any) (docgen.YAMLType, bool) {
	return ForType(reflect.TypeOf(in))
}

func ForType(in reflect.Type) (docgen.YAMLType, bool) {
	if in.PkgPath() == "" {
		return docgen.YAMLType{}, false
	}
	v, ok := global.finalDoc.Types[in.PkgPath()+"."+in.Name()]
	return v, ok
}

func ForMethod(method reflect.Value) (docgen.YAMLMethod, bool) {

	name := runtime.FuncForPC(method.Pointer()).Name()
	name = strings.TrimSuffix(name, "-fm")

	if name == "" {
		return docgen.YAMLMethod{}, false
	}
	lookup := name
	// try looking up func on a method if it looks like it
	if strings.Count(lookup, ".") > 1 {
		lastDotIdx := strings.LastIndex(lookup, ".")
		typeName := lookup[:lastDotIdx]
		funcName := lookup[lastDotIdx+1:]

		if t, ok := global.finalDoc.Types[typeName]; ok {
			m, ok := t.Methods[funcName]
			if ok {
				return m, true
			}
		}
	}
	v, ok := global.finalDoc.Functions[lookup]
	return v, ok
}

// GlobalFile returns a final File. It is mutable, so don't change anything!!
// TODO make it immutable
func GlobalFile() *docgen.YAMLDoc {
	return global.finalDoc
}
