/*
Package docregistry provides a registry for documentation entities extracted from the comments.
Every docfile generated by the docgen tool is registered here.
*/
package docregistry

import (
	"github.com/utrack/pontoon/docgen"
	"gopkg.in/yaml.v3"

	"github.com/pkg/errors"
)

type registry struct {
	finalDoc *docgen.YAMLDoc
}

func newRegistry() *registry {
	return &registry{finalDoc: &docgen.YAMLDoc{
		Checksum: "no-global-checksum",
		Services: make(map[string]docgen.YAMLService),
		Types:    make(map[string]docgen.YAMLType),
	}}
}

var global = newRegistry()

// MustRegister registers the generated docfile in the global registry.
// It panics if the registration fails. The panic will contain the error description,
// source file name and line number.
func MustRegister(yaml string) {
	err := global.registerYaml(yaml)
	if err != nil {
		panic(errors.Wrap(err, "when registering generated docfile"))
	}
}

func (r *registry) registerYaml(yaml string) error {
	doc, err := parseYaml([]byte(yaml))
	if err != nil {
		return errors.Wrap(err, "when parsing YAML to YAMLDoc")
	}

	for k, v := range doc.Services {
		if _, ok := r.finalDoc.Services[k]; ok {
			// TODO deep compare and error when not equal
			return errors.Errorf("service '%v' already registered", k)
		}
		r.finalDoc.Services[k] = v
	}

	for k, v := range doc.Types {
		if _, ok := r.finalDoc.Types[k]; ok {
			// TODO deep compare and error when not equal
			return errors.Errorf("type '%v' already registered", k)
		}
		r.finalDoc.Types[k] = v
	}

	return nil
}

func parseYaml(in []byte) (*docgen.YAMLDoc, error) {
	var ret docgen.YAMLDoc

	err := yaml.Unmarshal([]byte(in), &ret)
	return &ret, err
}

func ForType(name string) (docgen.YAMLType, bool) {
	v, ok := global.finalDoc.Types[name]
	return v, ok
}

func ForService(name string) (docgen.YAMLService, bool) {
	v, ok := global.finalDoc.Services[name]
	return v, ok
}

// GlobalFile returns a final File. It is mutable, so don't change anything!!
// TODO make it immutable
func GlobalFile() *docgen.YAMLDoc {
	return global.finalDoc
}