package main

import (
	"bytes"
	"text/template"
)

type tplRequest struct {
	PkgPath string
	PkgName string
	Content string
}

var tpl = template.Must(
	template.New("").Parse(
		`
// Code generated by utrack/pontoon. DO NOT EDIT.
// Source: {{ .PkgPath }}

package {{ .PkgName }}

const OpenAPI = ` + "`{{ .Content }}`",
	))

func tplGen(req tplRequest) ([]byte, error) {

	buf := bytes.NewBuffer(nil)

	err := tpl.Execute(buf, req)
	return buf.Bytes(), err
}
