// Code generated by github.com/utrack/pontoon/docgen. DO NOT EDIT.

package petstore

import (
	"github.com/utrack/pontoon/docgen/docregistry"
)

func init() {
	docregistry.MustRegister(docYAML)
}

const docYAML = `checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
types:
  Category:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: Category
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 17
    comment: |
      Category represents a pet category
    fields:
      - name: ID
        type: int64
        comment: |
          ID is a unique category ID.
        tags: json:"id"
      - name: Name
        type: string
        comment: |
          Name is the category name; non-unique.
        tags: json:"name"
    is_struct: true
  CreatePetRequest:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: CreatePetRequest
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 40
    comment: |
      CreatePetRequest represents a request to create a new pet
    fields:
      - name: Pet
        type: github.com/utrack/pontoon/examples/petstore.CreatePetRequestPet
        comment: |
          Pet is the pet's details
        tags: in:"body=json"
    is_struct: true
  CreatePetRequestPet:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: CreatePetRequestPet
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 45
    fields:
      - name: Name
        type: string
        comment: |
          Name is the pet's name.
        tags: json:"name"
      - name: Category
        type: github.com/utrack/pontoon/examples/petstore.Category
        comment: |
          Category is this pet's category.

          A new category is created if it's not found by ID.
        tags: json:"category"
      - name: Tags
        type: '[]github.com/utrack/pontoon/examples/petstore.Tag'
        comment: |
          Tags are the freeform tags of this pet.
        tags: json:"tags"
        is_array:
          type: github.com/utrack/pontoon/examples/petstore.Tag
      - name: Status
        type: github.com/utrack/pontoon/examples/petstore.Status
        comment: |
          Status is this pet's status in the store.

          docgen: enum
        tags: json:"status"
    is_struct: true
  ErrorResponse:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: ErrorResponse
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 86
    comment: |
      ErrorResponse represents an error response
    fields:
      - name: Code
        type: int
        tags: json:"code"
      - name: Message
        type: string
        tags: json:"message"
      - name: Details
        type: string
        tags: json:"details,omitempty"
    is_struct: true
  ListPetsRequest:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: ListPetsRequest
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 68
    comment: |
      ListPetsRequest represents a request to list pets
    fields:
      - name: Page
        type: int
        comment: |
          Page is yadda yadda
        tags: in:"query=page"
      - name: PerPage
        type: int
        tags: in:"query=per_page"
      - name: Status
        type: github.com/utrack/pontoon/examples/petstore.Status
        tags: in:"query=status"
      - name: Category
        type: string
        tags: in:"query=category"
      - name: Tags
        type: '[]string'
        tags: in:"query=tags"
        is_array:
          type: string
    is_struct: true
  ListPetsResponse:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: ListPetsResponse
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 78
    comment: |
      ListPetsResponse represents a response containing a list of pets
    fields:
      - name: Items
        type: '[]github.com/utrack/pontoon/examples/petstore.Pet'
        tags: json:"items"
        is_array:
          type: github.com/utrack/pontoon/examples/petstore.Pet
      - name: TotalItems
        type: int64
        tags: json:"total_items"
      - name: Page
        type: int
        tags: json:"page"
      - name: PerPage
        type: int
        tags: json:"per_page"
    is_struct: true
  Pet:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: Pet
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 6
    comment: |
      Pet represents a pet in the store
    fields:
      - name: ID
        type: int64
        tags: json:"id"
      - name: Name
        type: string
        tags: json:"name"
      - name: Category
        type: github.com/utrack/pontoon/examples/petstore.Category
        tags: json:"category"
      - name: Tags
        type: '[]github.com/utrack/pontoon/examples/petstore.Tag'
        tags: json:"tags"
        is_array:
          type: github.com/utrack/pontoon/examples/petstore.Tag
      - name: Status
        type: github.com/utrack/pontoon/examples/petstore.Status
        tags: json:"status"
      - name: CreatedAt
        type: time.Time
        tags: json:"created_at"
      - name: UpdatedAt
        type: time.Time
        tags: json:"updated_at"
    is_struct: true
  Request:
    id: ""
    package: net/http
    name: Request
    file: /usr/lib/go/src/net/http/request.go
    line: 112
    is_struct: false
  ResponseWriter:
    id: ""
    package: net/http
    name: ResponseWriter
    file: /usr/lib/go/src/net/http/server.go
    line: 96
    is_struct: false
  Status:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: Status
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 31
    comment: |
      Status represents a pet's status in the store
    is_struct: false
  Store:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: Store
    file: /home/u/github/utrack/pontoon/examples/petstore/handlers.go
    line: 13
    comment: |
      Store is a simple in-memory pet store
    fields:
      - name: pets
        type: map[int64]github.com/utrack/pontoon/examples/petstore.Pet
        is_map:
          key: int64
          value: github.com/utrack/pontoon/examples/petstore.Pet
      - name: seq
        type: int64
    methods:
      CreatePet:
        comment: |
          CreatePet creates a new pet
        file: /home/u/github/utrack/pontoon/examples/petstore/handlers.go
        line: 26
        inputs: []
        outputs: []
      ListPets:
        comment: |
          ListPets lists all pets matching the given criteria
        file: /home/u/github/utrack/pontoon/examples/petstore/handlers.go
        line: 79
        inputs: []
        outputs: []
      UpdatePet:
        comment: |
          UpdatePet updates an existing pet
        file: /home/u/github/utrack/pontoon/examples/petstore/handlers.go
        line: 53
        inputs: []
        outputs: []
    is_struct: true
  Tag:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: Tag
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 25
    comment: |
      Tag represents a pet tag
    fields:
      - name: ID
        type: int64
        tags: json:"id"
      - name: Name
        type: string
        tags: json:"name"
    is_struct: true
  Time:
    id: ""
    package: time
    name: Time
    file: /usr/lib/go/src/time/time.go
    line: 139
    is_struct: false
  UpdatePetRequest:
    id: ""
    package: github.com/utrack/pontoon/examples/petstore
    name: UpdatePetRequest
    file: /home/u/github/utrack/pontoon/examples/petstore/types.go
    line: 61
    comment: |
      UpdatePetRequest represents a request to update a pet
    fields:
      - name: ID
        type: int64
        tags: in:"path=id"
      - name: Pet
        type: github.com/utrack/pontoon/examples/petstore.CreatePetRequestPet
        comment: |
          Pet is the new model of this pet.
        tags: in:"body=json"
    is_struct: true
`
