package docgen

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"sort"

	"github.com/pkg/errors"
	"gopkg.in/yaml.v3"
)

// YAMLDoc represents the YAML documentation format.
type YAMLDoc struct {
	Checksum string              `yaml:"checksum"`
	Types    map[string]YAMLType `yaml:"types"`
}

// Method represents a service method in YAML format.
type YAMLMethod struct {
	Comment string            `yaml:"comment,omitempty"`
	File    string            `yaml:"file"`
	Line    int               `yaml:"line"`
	Inputs  []YAMLMethodParam `yaml:"inputs"`
	Outputs []YAMLMethodParam `yaml:"outputs"`
}

type YAMLMethodParam struct {
	Name string `yaml:"name"`
	Type string `yaml:"type"`
}

// YAMLType represents a type in YAML format.
type YAMLType struct {
	ID       string                `yaml:"id"`
	PkgPath  string                `yaml:"package"`
	Name     string                `yaml:"name"`
	File     string                `yaml:"file"`
	Line     int                   `yaml:"line"`
	Comment  string                `yaml:"comment,omitempty"`
	Fields   []YAMLField           `yaml:"fields,omitempty"`
	Methods  map[string]YAMLMethod `yaml:"methods,omitempty"`
	IsStruct bool                  `yaml:"is_struct"`
}

// YAMLField represents a field in YAML format.
type YAMLField struct {
	Name       string          `yaml:"name"`
	Type       string          `yaml:"type"`
	Comment    string          `yaml:"comment,omitempty"`
	Tags       string          `yaml:"tags,omitempty"`
	Nullable   bool            `yaml:"nullable,omitempty"`
	IsMap      *YAMLFieldMap   `yaml:"is_map,omitempty"`
	IsArray    *YAMLFieldArray `yaml:"is_array,omitempty"`
	IsEmbedded bool            `yaml:"is_embedded,omitempty"`
}

type YAMLFieldArray struct {
	Type string `yaml:"type"`
}

type YAMLFieldMap struct {
	TypeKey   string `yaml:"key"`
	TypeValue string `yaml:"value"`
}

// GenerateYAML generates YAML documentation from service documentation.
func GenerateYAML(sourceFiles []string, auxTypes []*TypeDoc) ([]byte, error) {
	// Create YAML document
	yamlDoc := &YAMLDoc{
		Types: make(map[string]YAMLType),
	}

	for _, typeDoc := range auxTypes {
		t := YAMLType{
			//TODO ID:       typeDoc.ID,
			PkgPath:  typeDoc.Package,
			Name:     typeDoc.Name,
			File:     typeDoc.File,
			Line:     typeDoc.Line,
			Comment:  typeDoc.Comment,
			Fields:   make([]YAMLField, len(typeDoc.Fields)),
			IsStruct: typeDoc.IsStruct,
			Methods:  make(map[string]YAMLMethod),
		}

		for i, field := range typeDoc.Fields {
			t.Fields[i] = yConvertField(field)
		}

		for _, method := range typeDoc.Methods {
			t.Methods[method.Name] = yConvertMethod(method)
		}
		yamlDoc.Types[typeDoc.Name] = t
	}

	// Calculate checksum of source files
	h := sha256.New()
	files := make([]string, len(sourceFiles))
	copy(files, sourceFiles)
	sort.Strings(files)
	for _, file := range files {
		h.Write([]byte(file))
	}
	yamlDoc.Checksum = fmt.Sprintf("%x", h.Sum(nil))

	// Marshal to YAML
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(yamlDoc); err != nil {
		return nil, errors.Wrap(err, "encoding YAML")
	}

	return buf.Bytes(), nil
}

func GenerateGoFile(pkgName string, content []byte) []byte {
	ret := `// Code generated by github.com/utrack/pontoon/docgen. DO NOT EDIT.

package ` + pkgName + `

import (
	"github.com/utrack/pontoon/docgen/docregistry"
)

func init() {
	docregistry.MustRegister(docYAML)
}

const docYAML = ` + "`" + string(content) + "`\n"

	return []byte(ret)
}

func yConvertMethod(m FunctionDoc) YAMLMethod {
	ret := YAMLMethod{
		Comment: m.Comment,
		File:    m.File,
		Line:    m.Line,
		Inputs:  make([]YAMLMethodParam, len(m.Params)),
		Outputs: make([]YAMLMethodParam, len(m.Returns)),
	}

	for i, param := range m.Params {
		ret.Inputs[i] = YAMLMethodParam{
			Name: param.Name,
			Type: param.Type,
		}
	}

	for i, param := range m.Returns {
		ret.Outputs[i] = YAMLMethodParam{
			Name: param.Name,
			Type: param.Type,
		}
	}
	return ret
}

func yConvertField(field FieldDoc) YAMLField {

	tf := YAMLField{
		Name:       field.Name,
		Type:       field.Type,
		Comment:    field.Comment,
		Tags:       field.Tags,
		Nullable:   field.Nullable,
		IsEmbedded: field.IsEmbedded,
	}

	if field.IsMap != nil {
		tf.IsMap = &YAMLFieldMap{
			TypeKey:   field.IsMap.TypeKey,
			TypeValue: field.IsMap.TypeValue,
		}
	}
	if field.IsArray != nil {
		tf.IsArray = &YAMLFieldArray{
			Type: field.IsArray.Type,
		}
	}
	return tf
}
